Cura 8684 qt controls replacement buttons, actions & exclusivity
Ultimaker/Uranium pull request #774
Opened 2022-01-25 13:03 UTC by casperlamboo

2022-01-25 14:45 UTC, nallath requested changes

2022-01-25 21:13 UTC, casperlamboo commented on UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
> +        Label
https://github.com/Ultimaker/Uranium/pull/774/commits/541c6df49d6168f66bb1aca08957f3e3b29697f5

2022-01-27 13:38 UTC, Ghostkeeper approved these changes

2022-01-27 14:20 UTC, Ghostkeeper commented
`Wizard.qml` still has a few Controls1 buttons, but I deleted that file in another branch since it's not used anywhere. So it is not something we need to change.

2022-01-31 16:33 UTC, merged