[CURA-10722] Add 'additional settings providers' (Engine Plugins)
Ultimaker/Uranium pull request #890
Opened 2023-07-26 12:20 UTC by rburema

Plugins should now be able to add settings. (But not append enum-values to existing ones, that's another ticket.)

- (De)serialization works, including load/save.
- Keys are tagged/'namespaced' with provider type (just a plugin for now), unique id, version.
- Will be sent to engine (except you have to demangle the tagged/namespaced name a bit).
- Setting-formulas work (except for taking values of another plugin).
- Can add to an existing category, or create a new one.

See (now) also the accompanying front-end PR here: https://github.com/Ultimaker/Cura/pull/16305

2023-07-28 09:25 UTC, jellespijker requested changes
LGTM; As we discussed during the stand-up we will add functionality to the plugin system as a whole (both front-end and curaengine_plugins) which will allow to add settings by simply specify a path to a `json` file. Which will have setting entries such as they are defined in `fdmprinter.def.json`

2023-07-28 09:25 UTC, jellespijker commented on UM/Settings/DefinitionContainer.py
> +            category_parent = self.findDefinitions(key=force_category)
```suggestion
            category_parent = self.findDefinitions(key = force_category)
```

2023-07-28 09:25 UTC, jellespijker commented on UM/Settings/DefinitionContainer.py
> +                if len(self.findDefinitions(key=category)) > 0:
```suggestion
                if len(self.findDefinitions(key = category)) > 0:
```

2023-07-28 09:27 UTC, jellespijker commented
Also pinging @fieldOfView because I think he also could have some valuable insights on this PR and at the very least FYI

2023-07-28 13:25 UTC, fieldOfView commented
> Also pinging @fieldOfView 

'sup?

Hmm, I don't quite get why this would be necessary. Many of my plugins are adding settings that eventually also get sent to CuraEngine (which happily ignores them), then to be used in postprocessing. It is all a bit hacky (private method access), but has been working very well for years.

2023-07-28 17:42 UTC, rburema commented
@fieldOfView -- If you don't see the need to change for your own plugins, that's fine. We're basically using the same mechanism anyway, so we won't clash.

Since (other) people are (we hope) going to be writing engine-plugins (also), there is additional need to make a proper (non-hacky) way to define additional settings for engine plugins. -- We may trust _you_ with our internals, but that's not necessarily the case for _every_ developer out there.

Also to us these settings do not feel quite the same as plugin preferences, and we'd like the possibility of defining values for them in profiles (for ex.; a 'weird printer' plugin that comes with an engine part and a bunch of profiles for example).

Additionally, different plugins might have the same setting-definition name added. We tag/'sort-of-namespace' the settings internally so that they at least don't destabilize the system. A similar story for different versions of the same plugin that might have tweaked their setting-definition meanings.

2023-07-31 09:45 UTC, nallath requested changes
Apart from my other review comments; We need unit tests for this.

2023-07-31 09:45 UTC, nallath commented on UM/Settings/AdditionalSettingDefinitionAppender.py
> +
What is an additional settings defintions appender? When should one use it? (aka: I think that this needs documentation)

2023-07-31 09:45 UTC, nallath commented on UM/Settings/DefinitionContainer.py
> +    def appendAdditionalSettingDefinitions(self, additional_settings: Dict[str, Dict[str, Any]]) -> None:
Needs a bit of documentation. What is this doing? In what cases should one use this?

2023-07-31 09:45 UTC, nallath commented on UM/Settings/AdditionalSettingDefinitionAppender.py
> +def prependIdToSettings(tag_type: str, tag_id: str, tag_version: str, settings: Dict[str, Any]) -> Dict[str, Any]:
Consider making this a static function of the class. My main argument for it is that right now, the documentation (that is nice and extensive!) for this function takes away the attention of the documentation of the class. But the class should be the "meat" of what is going on (and thus, should probably be listed first)

2023-08-03 12:12 UTC, merged